// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJSIL1miyVf2BgkMVUdX4FgJVAYeLWN8U',
    appId: '1:419991739578:web:1af1067b957676d7597683',
    messagingSenderId: '419991739578',
    projectId: 'pocketwise-d2061',
    authDomain: 'pocketwise-d2061.firebaseapp.com',
    storageBucket: 'pocketwise-d2061.firebasestorage.app',
    measurementId: 'G-W3H9M566RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs4P_hI0BEE7Od3BsHJS9fPA3m6XQPbxE',
    appId: '1:419991739578:android:f9749b8d24574eac597683',
    messagingSenderId: '419991739578',
    projectId: 'pocketwise-d2061',
    storageBucket: 'pocketwise-d2061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt6EUffOs-YECreFvMxftNfvaArk-LSl0',
    appId: '1:419991739578:ios:a4db4b47166a6f2f597683',
    messagingSenderId: '419991739578',
    projectId: 'pocketwise-d2061',
    storageBucket: 'pocketwise-d2061.firebasestorage.app',
    iosClientId: '419991739578-1e3vd7oqisbl0okfha9rrjahd013vcmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt6EUffOs-YECreFvMxftNfvaArk-LSl0',
    appId: '1:419991739578:ios:a4db4b47166a6f2f597683',
    messagingSenderId: '419991739578',
    projectId: 'pocketwise-d2061',
    storageBucket: 'pocketwise-d2061.firebasestorage.app',
    iosClientId: '419991739578-1e3vd7oqisbl0okfha9rrjahd013vcmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJSIL1miyVf2BgkMVUdX4FgJVAYeLWN8U',
    appId: '1:419991739578:web:ef9e17ce316a6430597683',
    messagingSenderId: '419991739578',
    projectId: 'pocketwise-d2061',
    authDomain: 'pocketwise-d2061.firebaseapp.com',
    storageBucket: 'pocketwise-d2061.firebasestorage.app',
    measurementId: 'G-DXFTD4CB56',
  );
}
